version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: mongo_container_two
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    restart: always
    ports:
      - "9411:9411"
    networks:
      - backend

  service-reg:
    build:
      context: ./service-reg
    container_name: service_registry
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  userms:
    build:
      context: ./userms
    container_name: userms_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo_db
      - service-reg
      - zipkin
    networks:
      - backend

  trainms:
    build:
      context: ./trainms
    container_name: trainms_container
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo_db
      - service-reg
      - zipkin
    networks:
      - backend

  ticketms:
    build:
      context: ./ticketms
    container_name: ticketms_container
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo_db
      - service-reg
      - zipkin
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
